# Generated by Django 5.0.2 on 2024-12-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(blank=True, max_length=16)),
                ('Expiry_Date', models.CharField(blank=True, max_length=5)),
                ('Card_Name', models.CharField(blank=True, max_length=40)),
                ('security_code', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hotel_booking_date', models.DateField(auto_now_add=True)),
                ('hotel_booking_date_arrive', models.DateField()),
                ('hotel_booking_date_leave', models.DateField()),
                ('hotel_booking_adults', models.IntegerField(default=0)),
                ('hotel_booking_children', models.IntegerField(default=0)),
                ('hotel_booking_oap', models.IntegerField(default=0)),
                ('hotel_total_cost', models.FloatField(default=0)),
                ('hotel_points', models.IntegerField(default=0)),
                ('hotel_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
