# Generated by Django 5.0.2 on 2024-12-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_payment_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_booking_adults',
            new_name='booking_adults',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_booking_children',
            new_name='booking_children',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_booking_date_arrive',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_booking_oap',
            new_name='booking_oap',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_total_cost',
            new_name='booking_total_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_booking_date_leave',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_points',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_user_id',
        ),
    ]
