# Generated by Django 5.0.2 on 2024-12-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_hotel_booking_adults_booking_booking_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
