# Generated by Django 5.0.2 on 2024-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_booking_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_path',
            field=models.CharField(default='', max_length=10),
        ),
    ]
